version: '3.5'

services:

  web:
    container_name: phpgres-sample-web
    image: phpgres-sample-web
    build: ./docker/web
    ports:
      - "${EXTERNAL_HTTP_PORT}:80"
    volumes:
      - ./app/html:/var/www/html
    depends_on:
      - db
    networks:
      - backend

  db:
    container_name: phpgres-sample-db
    image: postgres:9.6
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${EXTERNAL_DB_PORT}:5432"
    volumes:
      - ./docker/pgsql:/docker-entrypoint-initdb.d
    networks:
      - backend

networks:
  backend:
    external:
      name: sample-backend
